<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-05T00:24:40 IST" name="Suite" finished-at="2023-11-05T00:25:01 IST" duration-ms="20993">
    <groups>
    </groups>
    <test started-at="2023-11-05T00:24:40 IST" name="PlaceOrder test" finished-at="2023-11-05T00:24:55 IST" duration-ms="15027">
      <class name="com.Utility.TestDefinitions">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.Utility.TestDefinitions@3899782c]" started-at="2023-11-05T00:24:40 IST" name="launchApplication" finished-at="2023-11-05T00:24:47 IST" duration-ms="6294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="placeOrder(java.util.HashMap)[pri:0, instance:com.Utility.TestDefinitions@3899782c]" started-at="2023-11-05T00:24:47 IST" name="placeOrder" data-provider="getData" finished-at="2023-11-05T00:24:55 IST" duration-ms="8455" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PostalCode=123, LastName=bbb, FirstName=aaa}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.Utility.TestDefinitions@3899782c]" started-at="2023-11-05T00:24:55 IST" name="teardown" finished-at="2023-11-05T00:24:55 IST" duration-ms="187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.Utility.TestDefinitions -->
    </test> <!-- PlaceOrder test -->
    <test started-at="2023-11-05T00:24:56 IST" name="ErrorValidations test" finished-at="2023-11-05T00:25:01 IST" duration-ms="5454">
      <class name="com.Utility.errorValidationsTests">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.Utility.errorValidationsTests@4ed5eb72]" started-at="2023-11-05T00:24:56 IST" name="launchApplication" finished-at="2023-11-05T00:25:00 IST" duration-ms="4507" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginValidation()[pri:0, instance:com.Utility.errorValidationsTests@4ed5eb72]" started-at="2023-11-05T00:25:00 IST" name="loginValidation" finished-at="2023-11-05T00:25:01 IST" duration-ms="549" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrec] but found [Incorrect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrec] but found [Incorrect]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.Utility.errorValidationsTests.loginValidation(errorValidationsTests.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.Utility.errorValidationsTests@4ed5eb72]" started-at="2023-11-05T00:25:01 IST" name="teardown" finished-at="2023-11-05T00:25:01 IST" duration-ms="201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.Utility.errorValidationsTests -->
    </test> <!-- ErrorValidations test -->
  </suite> <!-- Suite -->
</testng-results>
